export const ENV = {
    roomCapacity: 4,
    numOfQuestions: 7,
    pointsLostWrongAnswer: -1, 
    pointsFirstCorrectAnswer: 4, 
    pointsSecondCorrectAnswer: 3, 
    pointsThirdCorrectAnswer: 2, 
    pointsForthCorrectAnswer:1,
    pointsCorrectAnswer: 1, 
    waitingMessage:'waiting',
    progressMessage:'inProgress',
    finishedMessage:'finished',
    questionIntervalMs:10000,
    hostMessageIntervalMs:12000,
    ScoreBoardIntervalMs:6000,
    beforeGameIntervalMs:5000,
    num_of_tags:5,
  };