export enum PredefinedTags {
    Geography = "Geography",
    History = "History",
    Science = "Science",
    Art = "Art",
    Literature = "Literature",
    Mathematics = "Mathematics",
    Technology = "Technology",
    Music = "Music",
    Sports = "Sports",
    Cinema = "Cinema",
    Biology = "Biology",
    Physics = "Physics",
    Chemistry = "Chemistry",
    Economics = "Economics",
    Philosophy = "Philosophy",
    Politics = "Politics",
    Environment = "Environment",
    Health = "Health",
    Culture = "Culture",
    Languages = "Languages"
}
